### ISSUE TITLE
Installer fails to launch on Apple Silicon Macs

### ISSUE THREAD

**Issue by ianmartinez** [Captain-Chaos/WorldPainter#219] opened 2021-11-20 06:35 UTC
I have tried installing with both the latest JRE 8 and the JRE 17 and both fail on Apple Silicon (M1 Max) with this message:

<img width="1261" alt="Screen Shot 2021-11-19 at 9 44 01 AM" src="https://user-images.githubusercontent.com/8404676/142716247-068c8d22-9b58-4fe8-9d4a-c570d63b6680.png">

Whereas on my old Intel based Macbook with an identical Java configuration it runs just fine:

<img width="1218" alt="Screen Shot 2021-11-19 at 9 50 07 AM" src="https://user-images.githubusercontent.com/8404676/142716249-0993352e-2194-4ba6-9e65-3e2c35b9fa5d.png">

With newer releases of install4j, [the devs appear to address this](https://www.ej-technologies.com/blog/2020/11/support-for-macos-on-arm-apple-m1/). Using also the _jpackage_ packager included with the JDK should also work, as I've used it in the past.

**Comment by Captain-Chaos** [comment] 2021-11-20 15:50
Are you sure that is a recent download? I recently fixed a problem where it required _exactly_ Java 8, instead of Java 8 or later. I have already tried to upgrade to the latest version of Install4J, but encountered problems, but if necessary I will look into it again.

**Comment by ianmartinez** [comment] 2021-11-21 22:59
Yes this is the latest version of WorldPainter from the website and the latest version of Java 8 (Update 311) downloaded from Oracle's site.

**Comment by Captain-Chaos** [comment] 2021-11-22 12:00
Can you try it with the latest version of Java?

**Comment by Captain-Chaos** [comment] 2021-11-22 12:11
Also, is that the Intel or ARM version of Java (assuming Oracle provides both; I don't know if that is the case)?

**Comment by ianmartinez** [comment] 2021-11-22 15:16
Sadly, it doesn't appear to run with the latest Java either (Java 17). There's not a release of Java 8 that's specific to ARM but there is on Java 17:
<img width="1117" alt="Screen Shot 2021-11-22 at 8 50 50 AM" src="https://user-images.githubusercontent.com/8404676/142883602-6abebc97-af9b-421e-b6fd-1424fc921fef.png">

**Comment by andrazverdnik** [comment] 2022-03-31 17:45
Any news on this? I'm trying to run this on an M1 mac and once I installed both JRE and JDK the installer started working and installed the app.

When I launch the app though, it still returns the exact same error
<img width="372" alt="Screenshot 2022-03-31 at 19 45 14" src="https://user-images.githubusercontent.com/39854772/161117629-78d49e65-432f-4613-97d2-281ab2d211c7.png">
.

**Comment by Captain-Chaos** [comment] 2022-05-01 16:28
Sorry I never got back to you. Is this still relevant?

**Comment by andrazverdnik** [comment] 2022-06-14 15:38
Yes

**Comment by Captain-Chaos** [comment] 2022-06-14 18:54
Unfortunately I don't have a Mac, let alone an M1 Mac, so this is very hard to debug for me. Especially since other people with M1 Macs have it working.

**Comment by Captain-Chaos** [comment] 2022-06-14 18:56
Could you both try installing this JDK: https://www.azul.com/downloads/?version=java-17-lts&os=macos&architecture=arm-64-bit&package=jdk

Remove all other version of Java. This seems to be one of the most linked to M1 Java environments. Let me know if you can install and run WorldPainter on this.

**Comment by ImaSimp-MrYumYum** [comment] 2022-07-06 20:34
Had the same issue, installing the Azul JDK fixed it. 
Thanks for the support.

**Comment by Captain-Chaos** [comment] 2022-07-10 10:06
OK, so it seems the problem is that no M1 version of Java is installed. Other than the Azul one linked above, it appears that Oracle also has one these days: https://www.oracle.com/java/technologies/downloads/#jdk17-mac

I'm going to close this issue since it's not a bug in WorldPainter, but I have tried to improve the download page to hopefully better guide people to the correct version of Java.

**Closed by Captain-Chaos** 2022-07-10 10:06 UTC
