### ISSUE TITLE
1.13.2 Generated maps with option 'allow minecraft to populate terrain' are completely regenerated.

### ISSUE THREAD

**Issue by Vddox** [Captain-Chaos/WorldPainter#103] opened 2019-05-01 22:19 UTC
I created a world using a custom js script. The .world was created successfully with the terrain looking completely as expected and normal.

I then exported the world, with the following settings changed from default:
Caverns everywhere [y]
Chasms everywhere [y]
Caverns break the surface [y]
Allow minecraft to populate the entire terrain [y] - This disables 'resources everywhere'

Once the export is complete I loaded up the world into a 1.13.3 Spigot Paper server, using the Multiverse plugin to handle the actual import. Once the import completes and I tp to the world and find the terrain is being completely regenerated as it's loaded (according to the seed of the world in general settings) and is just a normal world after that.

I have tried changing the import method to changing the level-name value in server.properties to the exported map name - this made no difference.

I have also tried importing on multiple different server distributions:
Spigot Paper 1.13.2
Spigot 1.13.2
CraftBukkit 1.13.2
Vanilla 1.13.2

These all had the same effect.

I have tried exporting the world with the setting 'Allow minecraft to populate the entire terrain' disabled.
This results (after loading the map into a server) in a world that correctly represents what was built in worldpainter, except for the fact that there are no features generated on the surface of the world (trees, plants etc..).

I have tried exporting the map on two different distributions Fedora 29 and Ubuntu 18.10, the same results are observed.

The script i'm using is located here: https://github.com/MattiBorchers/MinecraftEarthMap
Worldpainter version: 2.5.12
Java version: 1.8.0_201

**Comment by Captain-Chaos** [comment] 2019-05-19 15:44
This is unfortunately behaviour of Minecraft 1.13 that WorldPainter can do nothing about. Apparently when it sees non-populated chunks during the migration of a 1.12 map it concludes it can just regenerate the entire chunk (which would normally be true since those would only be around the edges of the map where no player has yet been).

Note that what I describe is the behaviour of vanilla Minecraft 1.13. I don't know what Spigot or the plugin you mention bring to that, but it sounds like it might be a similar problem (although if it really is Spigot or that plugin doing it, you might be able to get them to add an option to change this behaviour).

If you use the beta with Minecraft 1.13 support (see the sticky post in the subreddit) it should work. Another thing you could try is to open the exported map in Minecraft 1.12 first, and visit all the areas to force the chunks to be loaded, and then load it in 1.13. **However** you should be warned that I have seen instances after doing that where Minecraft 1.13 will later regenerate some chunks anyway, even after they have already been visited in-game!

Since it's not a bug I'll close the issue, but feel free to ask questions on the subreddit or to file new issues if you feel there is a problem with WorldPainter.

**Closed by Captain-Chaos** 2019-05-19 15:44 UTC
