### ISSUE TITLE
Feature request: place half sunflowers with schematics

### ISSUE THREAD

**Issue by Taiyou06** [Captain-Chaos/WorldPainter#319] opened 2023-06-04 21:52 UTC
Like title says only the 2 tall sunflowers are visible
![image](https://github.com/Captain-Chaos/WorldPainter/assets/77050201/d46a18e0-674d-41bb-9f1f-499fe6f30c93)

**Comment by Taiyou06** [comment] 2023-06-04 22:00
For those who wanna test here are the schematics 
https://drive.google.com/file/d/1qOpctfH3xrfpPZlOUjEhM5dWo7Uu-AdN/view?usp=sharing

**Comment by Captain-Chaos** [comment] 2023-06-17 15:25
This is not a bug. Half plants are not allowed by Minecraft and would pop off when the block is updated, so WorldPainter removes them during post processsing just like other invalid blocks.

I've changed this to a feature request, as more people have suggested the possibility of allowing half plants.

**Comment by Captain-Chaos** [comment] 2023-06-23 10:58
Duplicated by #306

**Comment by Captain-Chaos** [comment] 2023-06-23 11:01
I think it makes sense, as someone already suggested, to allow this when "remove from invalid blocks" is turned off in the Post Processing tab. Of course that would mean that _no_ plants would be removed from invalid blocks any more, meaning you would have to be extra careful where you places plants with Custom Object layers. Would that be satisfactory, @Taiyou06? @ALingll?

**Comment by Captain-Chaos** [comment] 2023-06-23 13:51
I've decided just to do this. It will be in the next release. If you want half sunflowers (or half of other double-high plants), you can now uncheck "remove from invalid blocks" on the Post Processing tab of the relevant dimension on the Export screen, and WorldPainter will not remove them. Of course that does mean you will have to be more careful where you paint Custom Object layers with plants.

**Closed by Captain-Chaos** 2023-06-23 13:51 UTC
Labels: enhancement
