### ISSUE TITLE
script bug: arguments and argv cannot receive negative parameter

### ISSUE THREAD

**Issue by Harveykang** [Captain-Chaos/WorldPainter#251] opened 2022-05-15 10:41 UTC
.toLevels(minHeight, maxHeight), minHeight<0 will cause the height map invert.

![image](https://user-images.githubusercontent.com/46108547/168467911-53b50d41-620a-484e-826e-b57c2dd3390c.png)
![image](https://user-images.githubusercontent.com/46108547/168468112-c8368276-3803-4122-acf5-6e98af02e87b.png)

**Comment by Captain-Chaos** [comment] 2022-05-15 12:33
I can't reproduce this. Those values in the screenshot are just comments; that doesn't mean those are the actual values of the variables. Can you double check that they are correct? If you still think there is a bug, please attach a complete set of files (script and height map) to reproduce.

**Comment by Harveykang** [comment] 2022-05-15 14:45
![image](https://user-images.githubusercontent.com/46108547/168478727-e34cc878-b33f-4b8b-81d4-876de0819815.png)
oh! seems because `arguments` and `argv` cannot receive negative numbers?

**Comment by Harveykang** [comment] 2022-05-15 14:54
![image](https://user-images.githubusercontent.com/46108547/168479257-dbd1a305-0d77-459e-9db1-13569bee3208.png)

**Comment by Captain-Chaos** [comment] 2022-05-15 16:30
Bizarre. I think that maybe it thinks they are options, because they start with a `-`. 😂 I'll look into it.

**Comment by Captain-Chaos** [comment] 2022-05-15 16:33
Yes, that is the case. They _are_ passed to the script, but in the `params` table. I'll add some logic so that negative numbers are treated as parameters rather than options.

**Comment by Captain-Chaos** [comment] 2022-05-15 16:40
This will be fixed in the next release.

**Closed by Captain-Chaos** 2022-05-15 16:40 UTC
