### ISSUE TITLE
[Could be a bug?] Water plants

### ISSUE THREAD

**Issue by WhiteWolfy** [Captain-Chaos/WorldPainter#254] opened 2022-05-21 04:45 UTC
Hello! Using latest version of WP (installed yesterday from official site). By some reason plant layer don't work for me in water. It does not place lilypads, seagrass and kelp and etc. It's a known issue or I did anything wrong? Previosly I had plants layer for ocean and it's worked, but it was placed about an year or two ago :D on old updates. Wondering if water plants broken on new updates? Or it require some additional movements to work? Please, help :(

**Comment by WhiteWolfy** [comment] 2022-05-21 04:51
Also about plants, some of them placing not where it supposed to be :D WP says it will be placed only where Minecraft let it. But vines for example placed on air, roots (from 1.18) placed just on block (instead of bottom of block) and etc. Plants layer is strange :D Also it could not be rendered on trees (at least custom ones), would be nice if plants will be rendered as last layer, to possible to render it on trees that was rendered before

**Comment by Captain-Chaos** [comment] 2022-05-24 10:23
I can't reproduce this. Can you upload a .world file that demonstrates this problem? Also let me know some coordinates to look at.

As to the last point:
- hanging plants are explicitly marked as such in on the Custom Plants layer screen, and it says "for ceilings and cave/tunnel roofs" right there. If you use them anyway in non-hanging contexts that's your own responsibility. 😉
- you can change the order in which the layers are exported on the Custom Layers tab of the Export screen.

**Comment by WhiteWolfy** [comment] 2022-05-24 13:50
Hello! Thanks for answer! I did not saw anything about hanging plants like you mentioned above, strange! But I agree that then it was my fault, sorry! 
Also about layers order, will it make vines rendered on custom trees then? I'll try, hope that can work, thanks! May be it will even fix water problem then, if WP will detect here is water already, and may be it will place plants on it correct then!

**Comment by Captain-Chaos** [comment] 2022-05-25 09:51
No, unfortunately the Plants layer doesn't place plants on other objects. If you want vines on your custom trees you will have to modify the actual custom objects themselves to add vines to them.

**Comment by Captain-Chaos** [comment] 2022-05-25 09:52
Since this is not a bug I will close the issue now, but feel free to file a feature request for this.

**Closed by Captain-Chaos** 2022-05-25 09:52 UTC

**Comment by WhiteWolfy** [comment] 2022-05-26 01:00
Could I reopen that ticket for feature request or should I create new one?.. Thank you for you offering to ask for feature request, you're too kind. But I'm not really understand what exact I can ask from you, because I'm not really in technical part of your programm >,..,> But I will be really happy if water plants will work with custom layers, could I ask this one please?.. Vines on custom objects will be nice too, but I dare not to ask you for two features at once. I don't want to modify trees schematic because they used in different places, so I wanted to add some vines only in some areas, like deep in forest, and on swamps etc. I have big map (about 10k+ x 10k+ blocks) with a lot of trees, so editing all shematics gonna be pain in the !@# :D But water plants more important for me, cuz I really need to add some green things to my rivers, lakes and swamp >,..,> But here is another thing - launch date for my server is about two weeks from now, and I dare not to have hope that you can add feature for me in this period, I'm sure you're a busy man, making such huge software.. Then I'm not sure should I ask this feature or not, because if it will be released like after month or two, it will make no sense for me in near future, may be only later, when I will add some new continents on my map. But I think it will gonna helful for me and other people anyway.

Sorry for a long text. But if you have some free time and can make this feature, then please, it will be really nice >,..,> Anyway thank you for attention and giving answers!

**Comment by WhiteWolfy** [comment] 2022-05-26 01:01
Oh. Seems like it did not worked (I was wondering if it will reopen ticket or not). I'm gonna create new one then
