### ISSUE TITLE
[Bug] The change the preview pattern in "edit layers settings" stopped working correctly.

### ISSUE THREAD

**Issue by SkySem** [Captain-Chaos/WorldPainter#274] opened 2022-10-01 17:10 UTC
![image](https://user-images.githubusercontent.com/38987710/193420337-b679f342-cd11-47ca-ac3b-356254a561b0.png)
With the last update, the "generation" method for custom layers stopped working correctly. It only remembers the "first choice" and I can no longer change that to another option.
as soon as i choose my other option and press "ok" it "takes my new settings" and closes the window, but if i check the layer again it will have the old settings

**Comment by Captain-Chaos** [comment] 2022-10-04 19:48
What do you mean by 'the "generation" method'? Could you give more detailed steps to reproduce please? As far as I can tell changing the preview pattern works correctly. Do note that it takes a second to update the preview.

**Comment by Captain-Chaos** [comment] 2022-11-19 16:32
Since you did not reply and this is working as far as I can tell I'm closing this. Feel free to file a new issue if you still think there is a bug.

**Closed by Captain-Chaos** 2022-11-19 16:32 UTC
