### ISSUE TITLE
[Features Request] Further support for exporting illegal plant blocks (especially half-plant blocks) in schematics

### ISSUE THREAD

**Issue by ALingll** [Captain-Chaos/WorldPainter#306] opened 2023-04-25 16:08 UTC
In fact, WorldPainter has greatly improved its ability to export illegal plant blocks compared to before. For example, floating grass and corals that are illegally placed can be well supported. However, I still encountered issues when trying to export a schematic that contains half-plant blocks (specifically, the top half of a lilac block). Note that all of the above experiments were first previewed using Chunky to ensure that the illegal blocks were not affected by updates caused by player entry into the game. At the same time, WorldPainter has disabled the "plants: remove from invalid blocks" option.

![image](https://user-images.githubusercontent.com/123755160/234334290-e03c7751-026a-445e-a488-20ddf5fdbb83.png)
![image](https://user-images.githubusercontent.com/123755160/234334406-e42e4bad-2f39-46fc-be23-8ac7d524c60e.png)

As you see above, illegally grass blocks were kept while half lilacs blocks were removed.

Additionally, I also found that even though the majority of the bottom half sunflower blocks were removed, a small number of blocks were still preserved in some chunks (this only occurred in a very small number of chunks). This indicates that the export of half-plant blocks is unpredictable and may be a bug.

![image](https://user-images.githubusercontent.com/123755160/234334197-f7a4e804-c49b-417a-8485-fc5309edb908.png)
![image](https://user-images.githubusercontent.com/123755160/234337180-4b9d6ee3-5d72-4338-9e71-c9de2ad112f6.png)

I have recently been creating a schematics package for WorldPainter based on illegal plant blocks (it is open-sourced on GitHub along with other packages). Illegal plant blocks can be used to create many stunning effects, such as using lower sunflower blocks to simulate plant stems. This issue has been bothering me for a while now, as I am unable to apply these schematics in WorldPainter. I am not sure if it is due to my setting errors, so please correct me if I am wrong.

![default_2023-04-21_00-38-57-40](https://user-images.githubusercontent.com/123755160/234336361-01dd7609-8a53-46a6-97aa-fe16b5ac593d.png)

I have send this problem in reddit to discuss days before, and some of the reply may be helpful(https://www.reddit.com/r/Worldpainter/comments/12t09oi/how_to_load_shcems_with_half_plants_correctly/?utm_source=share&utm_medium=web2x&context=3)

**Comment by Captain-Chaos** [comment] 2023-06-23 10:58
Closing as a duplicate of #319, even though that came later, since I already engaged with that one.

**Closed by Captain-Chaos** 2023-06-23 10:58 UTC
