### ISSUE TITLE
Custom Terrain Duplication

### ISSUE THREAD

**Issue by frogocomics** [Captain-Chaos/WorldPainter#34] opened 2016-11-16 15:34 UTC
I'm working with some layered terrains, and when I'm editing one custom material, it duplicates another one after I click okay. (I don't know how to describe it very well, it should be painfully obviously after you try it for yourself.)

**Comment by Captain-Chaos** [comment] 2016-11-20 22:10
I can't reproduce this. When I create two layered custom terrains I can edit them both without observing any duplication, painfully obvious or otherwise.

If you want to help me find this problem, you're going to have to be a lot more precise. I'm sure you can appreciate that I can't read your mind and don't have the time to hunt around trying things out looking for bugs. [Here](http://www.chiark.greenend.org.uk/~sgtatham/bugs.html)'s a good article about writing good bug reports.

I'm closing this issue for now, but feel free to submit a new one if you can reproduce it, with some comprehensive steps to reproduce.

**Closed by Captain-Chaos** 2016-11-20 22:10 UTC
Labels: bug, invalid

**Comment by frogocomics** [comment] 2016-11-21 15:34
Reopen please, I'll get a video.

**Comment by Captain-Chaos** [comment] 2016-11-27 13:12
No need to keep the issue around for that. A video would be ideal; once 
you have one, feel free to file a new issue!

Kind regards,
Captain_Chaos

**Comment by Captain-Chaos** [comment] 2016-12-09 22:01
Note that release 2.3.2 fixes a QoL issue that links custom terrains to the same custom material if you export and import them. Could that have been your issue too?
