### ISSUE TITLE
Does not install on MacBook Mojave

### ISSUE THREAD

**Issue by D3RPSTROYER** [Captain-Chaos/WorldPainter#85] opened 2018-12-07 01:05 UTC
Ive tried many time installing world painter on my 
MacBook Pro (Mid-2015)

it keeps saying the installer is damaged and should be deleted

**Comment by Captain-Chaos** [comment] 2018-12-25 17:54
This is a known issue, which unfortunately I can't reproduce (I _can_ install WorldPainter on my MacBook Pro with Mojave) and therefore is hard to investigate. Needless to say, the installer is _not_ damaged. It is however not signed with a certificate purchased from Apple, and Apple does not like that.

Have you tried configuring Gatekeeper to allow the installation by following [these](http://osxdaily.com/2016/09/27/allow-apps-from-anywhere-macos-gatekeeper/) instructions?

**Comment by frambinni** [comment] 2019-01-05 22:17
@D3RPSTROYER It installs after disabling GateKeeper. I strongly recommend that you re-enable GateKeeper after installing the program.

**Comment by Captain-Chaos** [comment] 2019-01-07 10:22
Since you didn't get back to me, and according to others such as @frambinni (thanks!) disabling Gatekeeper works, I'm going to close this issue. Feel free to open a new one if you still have problems.

**Comment by Captain-Chaos** [comment] 2019-01-07 10:23
@frambinni Did you follow those instructions I linked to to disable Gatekeeper, or something else?

**Closed by Captain-Chaos** 2019-01-07 10:22 UTC

**Comment by frambinni** [comment] 2019-01-09 00:54
@Captain-Chaos I followed the instructions linked above.
