### ISSUE TITLE
Custom terrain angles wrong

### ISSUE THREAD

**Issue by frogocomics** [Captain-Chaos/WorldPainter#33] opened 2016-11-16 06:46 UTC
When I set the custom terrain angles for a terrain, it changes after I click okay. Reproduce: Change custom terrain angles and open it again. It should have changed.

**Comment by Captain-Chaos** [comment] 2016-11-16 10:00
Could you give me steps to reproduce?

**Comment by Captain-Chaos** [comment] 2016-11-16 10:00
Also it sound like you're describing to separate bugs. If so could you create separate issues for them? Thx! :)

**Comment by Captain-Chaos** [comment] 2016-11-20 21:49
I found and fixed the bug. It will be in the next release. Thanks for helping find and fix this bug.

Bizarrely, it has been in the code since April 2015. You must be the first one since then using sloping layered custom materials...

**Closed** 2016-11-25 11:54 UTC
Labels: bug
