### ISSUE TITLE
Question: Merge with map on remote server

### ISSUE THREAD

**Issue by LittleLigr** [Captain-Chaos/WorldPainter#331] opened 2023-07-07 18:23 UTC
Hi! I am planning my new MC server, so I decided to try make updatable server map. I host it on vps server and link from my pc on Windows. If I try to import map in  WP - no problems. But if I try Merge something in alredy existing remote map - I get "Map in use" error. Is it possible to fix it, or not?
Thank you)

**Comment by Captain-Chaos** [comment] 2023-07-08 07:45
This isn't really the place for support requests, the official subreddit or unofficial Discord are better places for that, so I'll close this ticket.

Having said that, you get the "map in use" error if WorldPainter can't move the map directory to the backups directory. Usually that is because there are files open in the directory, for example because Minecraft is still running. If you have the Minecraft client running that might be it. If not, then perhaps something else is keeping the directory locked. It could also be something on the server. Is the server still running, for example?

Or perhaps the problem is that the map directory is on a network mount and the backups directory is not, so that WorldPainter can't move the map directory across the different file systems. In that case you could try mounting at a higher level so that the backups directory is also on the network share.

If that doesn't work then you'll probably have to copy the map locally and merge locally, and then copy the result to the network mount manually. In fact that is probably a better idea anyway, because WorldPainter does a lot of random reading and writing to these files, which is likely to be very slow on a network mount.

**Closed by Captain-Chaos** 2023-07-08 07:45 UTC
