### ISSUE TITLE
tree schematics made in 1.19.3+ are broken with leaves showing pourple in preview and when placed as object layer on map they don't appear on the map

### ISSUE THREAD

**Issue by Ratchet97** [Captain-Chaos/WorldPainter#318] opened 2023-06-01 19:23 UTC
Self explenatory title. Here are schematics I made for testing and reproducing the bug.

[oak_tree_schematic_1+19+3_bug.zip](https://github.com/Captain-Chaos/WorldPainter/files/11628782/oak_tree_schematic_1%2B19%2B3_bug.zip)

![image](https://github.com/Captain-Chaos/WorldPainter/assets/48301568/c771bd71-2ce1-45ad-96dd-3d9d4e0edb59)
![image](https://github.com/Captain-Chaos/WorldPainter/assets/48301568/4204b8cb-061e-4607-9792-a2a789cb9b32)

**Comment by Captain-Chaos** [comment] 2023-06-17 15:09
The purple blocks are harmless and just affect the preview. It's because the blocks have the waterlogged property, which they did not use to have in previous versions of Minecraft. I'll fix the preview in the next release.

I can't reproduce the issue with them not exporting. This single object you sent me exports fine if I put it in a custom object layer and paint it on a simple test map.

If you're sure there's an issue, could you please provide a small .world file which demonstrates it when exported?

**Comment by Captain-Chaos** [comment] 2023-06-23 09:57
Since I didn't hear back from you'll I'll consider this fixed and close it. Feel free to open a new ticket if you still have issues.

**Closed by Captain-Chaos** 2023-06-23 09:57 UTC
