### ISSUE TITLE
GUI randomly bugs out

### ISSUE THREAD

**Issue by navett52** [Captain-Chaos/WorldPainter#19] opened 2016-08-01 21:40 UTC
![worldpainterbug](https://cloud.githubusercontent.com/assets/15176024/17309880/17417b46-580f-11e6-80ce-d2290264636a.png)
As I use world painter sometimes the GUI decides to throw a fit and bugs out. I'm not sure why this happens. It seems to be happening at completely random times as well.

**Comment by Captain-Chaos** [comment] 2016-08-07 15:11
That doesn't look like it can be a bug in WorldPainter. Looks like it might be a bug in Java, or a problem with your video driver. Try updating both of them to the latest version.

If that doesn't help, you might try whether selecting a different hardware acceleration method on the Performance tab of the Preferences screen helps.

**Comment by navett52** [comment] 2016-08-08 03:51
Ok, I'll look into it. Hopefully one of these works cause this drives me insane when I'm trying to work on a map and then suddenly this happens. Thanks for the advice.

**Comment by trienow** [comment] 2016-08-08 10:21
I am having these problems as well. For me it happens, as soon as I open a combobox, and it's boundaries leave the containing window.
Luckily, in World Painter it doesn't seem like the Windows are locked, so I resize them, as a temporary fix. I tried researching the problem, but didn't find much unfortunately.

**Comment by Captain-Chaos** [comment] 2016-08-08 15:14
@trienow That definitely sounds like a Java/Swing bug. If the combox doesn't fit in the containing window it has to be painted in a different, more expensive way (as a separate window), which seems like it's triggering this bug. Have you tried upgrading your video driver and Java and/or experimenting with different 3D acceleration methods?

**Comment by Captain-Chaos** [comment] 2016-08-08 15:16
@navett52 Could that be what is triggering this bug for you as well, opening a combobox which doesn't fit in the containing window?

**Comment by Captain-Chaos** [comment] 2016-08-08 17:12
@trienow @navett52 What are your OS / system specs?

**Comment by trienow** [comment] 2016-08-08 21:56
> (...) Have you tried upgrading your video driver and Java

I tried updating it first, then after it did not help, installing an older Version. Though in the end I went back to the newest, because rolling it back had no effect.
I installed 8u101, then 8u102 JDK. No difference.

> (...) experimenting with different 3D acceleration methods?

Good Point. I found some Settings in your ```Preferences/Performance``` Tab.
```Default``` and ```Direct 3D``` make the combobox bug out.
```OpenGL``` and ```Unaccelerated``` work just fine. Thanks :)

> What are your OS / system specs?

Even though, I think I found a fix, I'll give you the info for reference.

Specification | Value
------------ | -------------
OS | Windows 10 Pro
Type | 64-Bit
Graphics Card | GeForce GTX 1070
Graphics Card Driver Version | 368.81 (newest)
Resolution | 2560x1440 120Hz
Processor | Intel Core i7-6700K
Java version | 8u102


Do you have any knowledge of a command line option I could use for other programs that have the same problem? I tried a few from the oracle troubleshooting site, but since I have limited understanding of JAVA I could only guess, what they were doing.

Thanks anyway

**Comment by Captain-Chaos** [comment] 2016-08-09 09:19
@trienow Thanks! Definitely a bug in Java's Direct3D implementation then (which is almost certainly what it uses for Default too). The weird thing is that I have almost the identical configuration to you, and for me it works fine. There must be some additional factor.

There's probably not a lot more I can do than to document this as a known problem. At least there is a workaround. Is the performance still acceptable when you set it to OpenGL or Unaccelerated?

If those other programs are Java programs then there are some VM options you could set to emulate what WorldPainter does when you make those selections. For OpenGL, WorldPainter sets the following VM options:

```
-Dsun.java2d.opengl=True
```

For Unaccelerated, it sets the following options:

```
-Dsun.java2d.d3d=false
-Dsun.java2d.opengl=false
-Dsun.java2d.xrender=false
-Dapple.awt.graphics.UseQuartz=false
```

**Comment by trienow** [comment] 2016-08-09 18:28
> Is the performance still acceptable when you set it to OpenGL or Unaccelerated?

There does not seem to be a decrease in performance.

> There must be some additional factor.

Maybe graphics for 3D settings in the control panel? I have set mine to their defaults. Have you changed anything?

> There's probably not a lot more I can do (...)

No problem. At least we found something. Though I would be interested if changing those settings helps @navett52.

**Comment by Captain-Chaos** [comment] 2016-08-10 09:10
> Maybe graphics for 3D settings in the control panel? I have set mine to their defaults. Have you changed anything?

@trienow The NVidia control panel? No, defaults just like you. I do have a 980 Ti instead of a 1070. I wouldn't expect that to make a difference, but who knows. I think I'll leave it at this and add an item to the troubleshooting page on the wiki.

Thanks for your help!

**Comment by navett52** [comment] 2016-08-11 23:27
I updated Java and my graphics drivers. I have windows 10 and two AMD Radeon R9 graphics cards. I tried changing the acceleration method to Direct3D first and that didn't helps so then I tried changing it to the Open3D (or whatever its called) but now I cannot see anything whenever a new window pops up.
![blankpreferences](https://cloud.githubusercontent.com/assets/15176024/17608305/a4baf62c-5ff9-11e6-9f35-dd0412602d5b.PNG)

**Comment by navett52** [comment] 2016-08-11 23:29
At this point I can't use world painter. Since every time I try to do something that requires a new window and it's blank I can't do things like make new layers. I did try uninstalling and reinstalling and that didn't work.

**Comment by Captain-Chaos** [comment] 2016-08-13 10:35
@navett52 If you delete the config file (%APPDATA%\WorldPainter\config) that should reset the acceleration type so you can at least get to the Preferences again.

Could you then check whether the trigger for the bug is the same as for trienow, i.e.: opening a combox (drop down list) which doesn't fit in the window? Also, could you try whether the Unaccelerated "acceleration" type fixes the problem?

**Comment by navett52** [comment] 2016-08-14 03:52
@Captain-Chaos I'll give it a shot and let you know. Thanks!

**Comment by Captain-Chaos** [comment] 2016-08-17 21:55
How are you getting on @navett52? Has setting the acceleration method to unaccelerated fixed the problem?

**Comment by navett52** [comment] 2016-08-18 18:52
@Captain-Chaos I haven't gotten on to work on my project enough to really tell if that's worked. This Saturday I should be able to give you a good answer as to whether or not I think setting the acceleration method to unaccelerated will fix the problem.

**Comment by Captain-Chaos** [comment] 2016-11-20 22:32
How's it going @navett52? I think it's clear that this is not a bug in WorldPainter, but various bugs and/or interactions between Java and the video driver, so I think I'm going to close the bug anyway, as there doesn't appear to be anything I can do about it in WorldPainter.

**Comment by navett52** [comment] 2017-01-06 16:36
@Captain-Chaos , If I keep it as unaccelerated it seems to work fine. Thanks for being responsive/very helpful!

**Comment by Captain-Chaos** [comment] 2017-01-08 16:48
My pleasure. I'm closing the bug now.

**Closed by Captain-Chaos** 2017-01-08 16:48 UTC
Labels: bug

**Comment by trienow** [comment] 2017-03-03 18:06
I know it is closed now, but after a BSOD I needed to reset all programs on my computer.
Today I installed WorldPainter again and immediately tested, if the error still persists and it does not.
I guess resetting everything on the PC makes this work again. Just wanted to mention.
