### ISSUE TITLE
Unusual program behavior on RPi4

### ISSUE THREAD

**Issue by Rak1ta** [Captain-Chaos/WorldPainter#259] opened 2022-05-27 11:51 UTC
On Raspberry Pi 4 Debian 10 Buster 32 bit, the program only runs with a certain version of java. If something other than 11 is selected, then nothing works.

There are no error messages, but there is a video.
[ScreenRecorderProject1.zip](https://github.com/Captain-Chaos/WorldPainter/files/8786424/ScreenRecorderProject1.zip)

**Comment by Captain-Chaos** [comment] 2022-05-27 20:13
Thanks. _Very_ strange behaviour. It seems that the menu's work for a little while, but even they stop working after a while?

Could you please upload your log file (`~/.worldpainter/logfile0.txt`)?

One thing that springs to mind is that WorldPainter's tablet support sometimes malfunctions in exotic environment. Could you try disabling that by adding the line:
```
-Dorg.pepsoft.worldpainter.disableTabletSupport=true
```
...to `/opt/worldpainter/worldpainter.vmoptions`? Let me know if that makes a difference.

**Comment by Rak1ta** [comment] 2022-05-27 20:30
> menu's work for a little while,

When the mouse cursor passes over the map it crashes.

Did not help.
[logfile0.txt](https://github.com/Captain-Chaos/WorldPainter/files/8789584/logfile0.txt)

**Comment by Captain-Chaos** [comment] 2022-05-28 08:48
> When the mouse cursor passes over the map it crashes.

And by crashes you mean it hangs?

Does it work in Safe Mode?

**Comment by Rak1ta** [comment] 2022-05-28 09:34
> Safe Mode

Sorry, I don't understand this. What needs to be done?

**Comment by Captain-Chaos** [comment] 2022-05-28 10:10
> Sorry, I don't understand this. What needs to be done?

It should be a separate Start menu/Desktop entry. Or you can start it from the command line with the parameter `--safe`.

**Comment by Rak1ta** [comment] 2022-05-28 10:52
@Captain-Chaos did not help
[logfile0.txt](https://github.com/Captain-Chaos/WorldPainter/files/8790985/logfile0.txt)

**Comment by Captain-Chaos** [comment] 2022-05-28 13:18
I'm running out of ideas then. It seems likely that this is a problem with Java and/or the video driver that I can't do anything about. The problem is not Java 16; it runs fine on Java 16 on Windows. Nor is it the word size; it also runs fine on 32-bits on Windows. It's some unique combination of factors to that version of Java on that hardware.

If you can give me steps to reproduce this without needing an actual Raspberry Pi (I do have Oracle VirtualBox) I can look a little deeper into it, but without that I'm afraid there's not much I can do.

**Comment by Captain-Chaos** [comment] 2022-05-28 13:42
If you run WorldPainter from the command line, is there any additional output when the problem occurs? Any stack trace or error message?

**Comment by Captain-Chaos** [comment] 2022-05-28 14:03
Also of course, Java 16 is out of support! Java 17 is the current LTS version. Does it work on Java 17?

**Comment by Rak1ta** [comment] 2022-05-28 14:57
@Captain-Chaos 

Debian Buster 32 bit - works.
```
pi@raspberrypi:~ $ java --version
openjdk 17.0.3 2022-04-19
OpenJDK Runtime Environment Temurin-17.0.3+7 (build 17.0.3+7)
OpenJDK Server VM Temurin-17.0.3+7 (build 17.0.3+7, mixed mode, sharing)
```

Please wait I will check on Bullseye 32bit (I will upload a copy of ssd)

**Comment by Captain-Chaos** [comment] 2022-05-28 19:02
It doesn't look there is anything I can do about it from my side then. It seems likely the problem is some kind of bug or compatibility problem in that specific AdoptOpenJDK runtime. Since I can't reproduce it, it is a rare problem, the runtime in question is end-of-life, and there is a good workaround (the `INSTALL4J_JAVA_HOME_OVERRIDE` variable), I'm afraid I have no choice but to close this.

**Closed by Captain-Chaos** 2022-05-28 19:02 UTC
