### ISSUE TITLE
Error while exporting minecraft map

### ISSUE THREAD

**Issue by KingSnailtan** [Captain-Chaos/WorldPainter#102] opened 2019-04-29 10:04 UTC
I have made a custom object layer with .schem files. This may have something todo with that.
After deleting them, the Error still happened.

How to reproduce:
Export to new Minecraft world.

The Error:

java.lang.RuntimeException: I/O error while exporting world
	at org.pepsoft.worldpainter.ExportProgressDialog$1.execute(ExportProgressDialog.java:140)
	at org.pepsoft.worldpainter.ExportProgressDialog$1.execute(ExportProgressDialog.java:125)
	at org.pepsoft.util.swing.MultiProgressComponent$1.run(MultiProgressComponent.java:91)

Root cause:
org.xml.sax.SAXParseException: Content is not allowed in prolog.
	at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(null:-1)
	at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(null:-1)
	at org.jnbt.XMLTransformer.fromXML(XMLTransformer.java:31)
	at org.pepsoft.worldpainter.exporting.JavaWorldExporter.export(JavaWorldExporter.java:118)
	at org.pepsoft.worldpainter.ExportProgressDialog$1.execute(ExportProgressDialog.java:138)

WorldPainter version: 2.6.0.RC2 (20190428220559)

java.version: 1.8.0_211
java.vendor: Oracle Corporation
java.vm.version: 25.211-b12
java.vm.vendor: Oracle Corporation
java.vm.name: Java HotSpot(TM) 64-Bit Server VM
os.name: Windows 10
os.arch: amd64
os.version: 10.0
user.home: C:\Users\admin
user.dir: C:\Program Files\WorldPainter
user.country: DE
user.language: de

Free memory: 280509584 bytes
Total memory size: 625999872 bytes
Max memory size: 12352225280 bytes

World name: Insel
Seed: -8432911317091402117
Bounds: -25, -25 => 24, 24
Height: 256
Number of tiles: 2500
Layers in use: Annotations, Biome, Frost, My Custom Objects
Border: ENDLESS_WATER @ 62
Sub surface material: Stone
Water height: 62

Operation: Pencil
Radius: 144
Brush: Plateau Circle (radius=144, brushShape=CIRCLE, level=0.37)/Constant Circle (radius=0, brushShape=CIRCLE, level=1.0)
Level: 0.37/0.51
Zoom: 0
Hidden layers: [Annotations, Biome]

The Logfile
[logfile0.txt](https://github.com/Captain-Chaos/WorldPainter/files/3126902/logfile0.txt)

**Comment by Captain-Chaos** [comment] 2019-04-30 19:42
No, the problem is the flat mode preset. In Minecraft 1.13 that is no longer text; it is a complex binary structure. WorldPainter supports it, but in the form of XML (which it then translates to NBT), which I have yet to document or make convenient to use.

One thing you could do is create a Superflat world with your desired settings in Minecraft, Import it in WorldPainter and copy the flat mode preset from the Export screen.

Since this isn't actually a bug I'm going to close this issue, but feel free to ask further questions here or on the subreddit, or to file a new issue if you feel something is not working correctly.

**Closed by Captain-Chaos** 2019-04-30 19:42 UTC
