### ISSUE TITLE
Bug chunk

### ISSUE THREAD

**Issue by Natixe** [Captain-Chaos/WorldPainter#229] opened 2022-03-18 11:33 UTC
Hello,

I made a "Merge" on a map that I have modified and when I connect to it, some chunks are bugged. I made a "Change Height" where I put the value of shift to 12 to be able to raise my map of 12 block.

![image](https://user-images.githubusercontent.com/49234582/158995223-91efa921-7a3b-4ac6-860a-635bf2175eac.png)
![image](https://user-images.githubusercontent.com/49234582/158995291-44e66c0f-a3d5-4fa9-a15e-089b5d120754.png)
![image3](https://user-images.githubusercontent.com/49234582/158995326-f8a1fd0a-5679-4a7a-bd52-e3bddb8bf630.png)

**Comment by Captain-Chaos** [comment] 2022-05-01 16:26
Could it be that the chunks that were not raised had the Read-Only layer on them?

**Comment by Natixe** [comment] 2022-05-03 18:53
No I merged all the chunks of the map

**Comment by Captain-Chaos** [comment] 2022-05-04 15:52
Note that trying to raise an existing map is not really what this is meant for and it probably won't work as you expect. It won't raise the underground portion, for example; it just adds terrain on top of it.

However, if you really did not have the Read-Only layer anywhere, and did not make a tile selection for the Merge, it should have raised everything. Can you reproduce it? If so can you send me a Minecraft map, and a .world file to Merge with it, that demonstrates the problem?

**Comment by Captain-Chaos** [comment] 2022-05-25 10:06
Closing this since I did not get a response. Feel free to file a new issue if you still think there is a bug.

**Closed by Captain-Chaos** 2022-05-25 10:06 UTC
