### ISSUE TITLE
Offset, random mirror and random rotate functionality does not appear to apply to entities within custom object schematics

### ISSUE THREAD

**Issue by JamesRon** [Captain-Chaos/WorldPainter#268] opened 2022-08-09 21:11 UTC
**Offset, random mirror and random rotate functionality does not appear to apply to entities within custom object schematics**

**The observed effect is as follows:** 
When exporting a map with custom objects that contain entities (namely, armor stands, item frames, paintings) and any transformation is applied to that object (offset, mirror, rotation) the entities are not affected, leaving them in the 'old' locations while the rest of the blocks are moved/transformed. So you get an affect where your item frames and paintings break, armor stands are floating etc. All of your entities are in the wrong spot relative to the rest of the blocks. It seems like offset, rotate and mirror does not work for entities at all, at least for the WP version and MC versions listed below. When no offset, random rotate, random mirror is used, the schematic loads into the world perfectly and everything is in the right place.

**The steps to easily replicate are as follows:**
WP version used: 2.12
Minecraft version 1.19.2
custom object format: .nbt
Entities tested: armor stand, painting, item frame

1. create a minecraft world and in a clean/flat area create a test schematic mini build with a few item frames, an armor stand and a painting or two. I used a basic little platform that was 2 blocks deep and about 10x10 wide with some walls for item frames and paintings
2. Export the schematic using a structure block in-game(pretty simple, you just place a structure block down, set it to SAVE, set the dimensions and it's outlines so you can see if all your blocks are included). Your schematic is saved in the 'generated' folder in your minecraft world files
3. Go into worldpainter and create a custom object layer with your .nbt schematic as your normally would. At first you can turn off all offset, rotate and mirror to see what it looks like in game. Then switch random rotate, mirror and some offset on and observe the effect. You'll notice all the entities are not in the right locations as they weren't transformed like the blocks were

Notes:

Not sure if this was ever functional

Not sure if this is a WP or MC version thing potentially if it was functional in the past

Please let me know if anything is unclear or if you have any questions

**Comment by Captain-Chaos** [comment] 2022-08-11 08:21
Thanks. Could you attach such an .nbt file?

**Comment by JamesRon** [comment] 2022-08-11 15:38
> Thanks. Could you attach such an .nbt file?

Absolutely-- sample .nbt attached with screenshot of what the schematic should look like. Had to compress since github won't directly accept .nbt files.  
[test.zip](https://github.com/Captain-Chaos/WorldPainter/files/9309931/test.zip)

**Comment by Captain-Chaos** [comment] 2022-08-18 10:04
Thanks, that makes a big difference in the speed with which I can pick this up. For me, most of the item frames actually immediately pop off the walls in Minecraft even without any offset, rotation or mirroring. Does that not happen for you? If not, is there anything different about your environment; e.g. are you using completely vanilla Minecraft?

It may not matter, but I like to exactly reproduce the problem before delving into the cause, to avoid solving the wrong problem.

**Comment by Captain-Chaos** [comment] 2022-08-18 10:08
It looks like this nbt came from a PaperMC server, is that correct? If so, does the same thing happen with an nbt from a local client?

**Comment by Captain-Chaos** [comment] 2022-08-19 16:44
Never mind, I have been able to reproduce the problem (or at least, some problems having to do with the exporting of entities from custom objects). At least I can export your test object correctly with offsets, random rotation and mirroring now.

The fix will be in the next release. Part of the problem was some permanent damage to the metadata of the objects stored in the .world file, so you will have to reload the affected objects from disk in the Custom Object layer settings. Let me know after the next version is released whether this issue is resolved.

This is a very complicated subject, as every type of entity and tile/block entity has its own set of attributes that may affect its attitude. For example, the item rotation on item frames should also be mirrored, strictly speaking, but currently is not. Supporting them all may not be feasible, but let me know if anything substantial seems to be missing.

**Comment by JamesRon** [comment] 2022-08-20 07:31
@Captain-Chaos 
I do think I understand what you mean and I do believe the paintings were having issues even without any of the transformations. The armor stands however seem to directly/only affected by offset, rotation and mirroring. 

To answer your question I did create the .nbt in a Paper server world but loaded it into the game in normal vanilla MC local world. I will look out for this on the next release and report back to you what, if any issues i'm having. Thanks again!

**Closed** 2022-08-20 13:39 UTC
