### ISSUE TITLE
Lava and water pillars form after merging minecraft map

### ISSUE THREAD

**Issue by Cineminecraft** [Captain-Chaos/WorldPainter#86] opened 2018-12-11 07:56 UTC
Lava and water pillars form under existing (and contained) source blocks in my map. These pillars reach all the way to bedrock. but don't actually destroy blocks in their path, they're only placed in empty spaces, this is however still very annoying.

https://media.discordapp.net/attachments/207198135850631169/518833035144069131/2018-12-02_17.56.50.png
https://cdn.discordapp.com/attachments/207198135850631169/520302676911587358/2018-12-06_19.16.28.png

my minecraft version is 1.12.2 and my map was made around 1.7 I believe. I used the latest version of worldpainter. (2.5.8)
I have already tried turning off enforceBlockRules using the advanced options.

**Comment by Captain-Chaos** [comment] 2018-12-25 17:51
I've looked into it, and I'm afraid this is expected behaviour that is exactly the reason the Read Only layer exists, and that would be hard to fix.

What is happening is that on Import WorldPainter is detecting the source block as the water level for that column, but since the block below it is man-made it does not detect it as the terrain level; the _real_ terrain level below it, if any, is detected as the terrain level. WorldPainter does not have to concept of floating water, so in the WorldPainter world there is now a column of water there, with no way for WorldPainter to know when Merging the world that only the top block is supposed to be there.

Usually this is the behaviour you want, because it allows you to use WorldPainter to remove or add bodies of water, or change the water level of existing bodies of water. It doesn't mesh well with man made builds however.

As you can see it would be complicated to change this logic to fit your use case, which is hard to justify for a Merge operation which is advertised as destructive to builds.

One thing you could try is, after Importing the map, _removing_ the water altogether in that location using the Sponge tool. That would leave it dry after the Merge, but perhaps that is less onerous to fix?

**Comment by Captain-Chaos** [comment] 2019-01-13 09:54
Since you didn't get back to me I'm going to assume this is resolved to your satisfaction now and will close the issue. If you still think a bug exists or there is an improvement to be made, feel free to file a new issue!

**Closed by Captain-Chaos** 2019-01-13 09:54 UTC
