### ISSUE TITLE
"Custom world generator name not set" in 2.5.7

### ISSUE THREAD

**Issue by Dragonshadows** [Captain-Chaos/WorldPainter#81] opened 2018-10-17 13:05 UTC
I was trying to export part (425 tiles) of map to see how it looks in MC
Got strange error. Dunno how I managed to get it but I sorted it somehow and now exporting works ok for this world. Maybe I did something when created the map
Here is the error report WP game me

java.lang.IllegalArgumentException:_ Custom world generator name not set
	at org.pepsoft.worldpainter.exporting.JavaWorldExporter.export(JavaWorldExporter.java:48)
	at org.pepsoft.worldpainter.ExportProgressDialog$1.execute(ExportProgressDialog.java:138)
	at org.pepsoft.worldpainter.ExportProgressDialog$1.execute(ExportProgressDialog.java:125)
	at org.pepsoft.util.swing.MultiProgressComponent$1.run(MultiProgressComponent.java:91)

WorldPainter version: 2.5.7 (20180905223042)

java.version: 1.8.0_181
java.vendor: Oracle Corporation
java.vm.version: 25.181-b13
java.vm.vendor: Oracle Corporation
java.vm.name: Java HotSpot(TM) 64-Bit Server VM
os.name: Windows 10
os.arch: amd64
os.version: 10.0
user.home: 
user.dir: C:\Program Files\WorldPainter
user.country: US
user.language: en

Free memory: 1388135752 bytes
Total memory size: 3827302400 bytes
Max memory size: 13337886720 bytes

World name: GenWorld03-01
Seed: -985666580788671873
Bounds: -75, -75 => 74, 74
Height: 256
Number of tiles: 22500
Layers in use: 
Border: ENDLESS_WATER @ 63
Sub surface material: STONE_MIX
Water height: 63

Operation: Spray Paint
Radius: 260
Brush: Constant Circle (radius=260, brushShape=CIRCLE, level=0.51)/org.pepsoft.worldpainter.brushes.BitmapBrush@111ceb09
Level: 0.51/0.51
Zoom: -1
Hidden layers: [Biome]

**Comment by Captain-Chaos** [comment] 2018-12-27 15:56
Since you didn't get to back to me I'm going to close the issue. However if it does still happen please feel free to file a new issue. Try to include steps to reproduce in that case and/or, preferably, the actual .world file that is failing.

**Closed by Captain-Chaos** 2018-12-27 15:56 UTC
